# Generated by Django 5.0.1 on 2024-02-17 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='budget_limit',
            field=models.IntegerField(default=25000),
        ),
    ]
