# Generated by Django 5.0.1 on 2024-02-06 17:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_type', models.CharField(max_length=25)),
                ('category', models.CharField(choices=[('Food', 'Food'), ('Clothing', 'Clothing'), ('Transportation', 'Transportation'), ('Home', 'Home'), ('Bills', 'Bills '), ('Entertainment', 'Entertainment'), ('Household_goods', 'Household Goods'), ('personnel_needs', 'Personnel Needs'), ('Education', 'Education'), ('Sports', 'Sports'), ('Others', 'Others')], max_length=25)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('amount', models.IntegerField()),
                ('description', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
