# Generated by Django 5.0.1 on 2024-02-07 13:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income_type', models.CharField(max_length=25)),
                ('category', models.CharField(choices=[('Salary', 'Salary'), ('Sales', 'Sales'), ('Dividends', 'Dividends'), ('Rental', 'Rental'), ('Grants', 'Grants'), ('Refunds', 'Refunds'), ('Awards', 'Awards'), ('Others', 'Others')], max_length=25)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('amount', models.IntegerField()),
                ('description', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
