# Generated by Django 5.0.1 on 2024-02-03 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('food', 'Food'), ('clothing', 'Clothing'), ('transportation', 'Transportation'), ('home', 'Home'), ('bills', 'Bills '), ('entertainment', 'Entertainment'), ('household_goods', 'Household Goods'), ('personnel_needs', 'Personnel Needs'), ('education', 'Education'), ('sports', 'Sports'), ('others', 'Others')], max_length=25),
        ),
    ]
