# Generated by Django 5.0.1 on 2024-02-03 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_expense_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='product',
            new_name='expense_type',
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('Food', 'Food'), ('Clothing', 'Clothing'), ('Transportation', 'Transportation'), ('Home', 'Home'), ('Bills', 'Bills '), ('Entertainment', 'Entertainment'), ('Household_goods', 'Household Goods'), ('personnel_needs', 'Personnel Needs'), ('Education', 'Education'), ('Sports', 'Sports'), ('Others', 'Others')], max_length=25),
        ),
    ]
